/* Generated By:JavaCC: Do not edit this line. CSVReaderConstants.java */
package kabuLab.CSVReader;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface CSVReaderConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int DELIMITER = 1;
  /** RegularExpression Id. */
  int NEWLINE = 2;
  /** RegularExpression Id. */
  int MyEOF = 3;
  /** RegularExpression Id. */
  int CELL = 4;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"\\u001e\"",
    "\"\\u001d\"",
    "\"\\u0000\"",
    "<CELL>",
    "\"\\n\"",
    "\"\\r\"",
  };

}
